### ISSUE TITLE
Comments preview not working when addon enabled

### ISSUE THREAD

**Issue by raketentim** [Hemmingsson/Quick-Preview#1]
Nice addon! One issue: when enabled, it disables showing timed comments on hover, and as a result, replying to comments

**Comment by Hemmingsson** [comment]
Ah! Haven't noticed this before. Will make a fix for it. Thanks.

**Comment by Hemmingsson** [comment]
@raketentim The issue fixed in v2.0.0! Also don't forget to check the new preferences menu by clicking the extension icon :) Thanks for filing the bug!
